version: '3'
services:
  # unique service name
  web-server:
    # download nginx image tagged 1.17.1
    image: nginx:1.17.1
    # maps host port 8085 to web-server container port 8090
    ports:
      - "8085:8090"

  app-server:
    image: tomcat:9.0.12
    ports:
      - "8882:8080"